export enum RSPLSGAME_VALUES {
  ROCK = 'ROCK',
  SCISSORS = 'SCISSORS',
  PAPER = 'PAPER',
  LIZZARD = 'LIZZARD',
  SPOCK = 'SPOCK',
}

export const RSPLSGAME_VALUES_IMAGES_MAP = new Map<string, string>([
  [RSPLSGAME_VALUES.ROCK, 'rsp-rock.svg'],
  [RSPLSGAME_VALUES.SCISSORS, 'rsp-scissors.svg'],
  [RSPLSGAME_VALUES.PAPER, 'rsp-paper.svg'],
  [RSPLSGAME_VALUES.LIZZARD, 'rsp-lizzard.svg'],
  [RSPLSGAME_VALUES.SPOCK, 'rsp-spock.svg'],
]);

export interface GameModel {
  username: string;
  userWins: number;
  computerWins: number;
  lastPlayUser: RSPLSGAME_VALUES;
  lastPlayComputer: RSPLSGAME_VALUES;
}

export enum RSPLSGAME_RESULT_OPTIONS {
  TIE = 'TIE',
  USER_WIN = 'USER_WIN',
  COMPUTER_WIN = 'COMPUTER_WIN',
}

export const RSPLSGAME_RESULT_MESSAGES_MAP = new Map<string, string>([
  [RSPLSGAME_RESULT_OPTIONS.TIE, '¡TIE! :/'],
  [RSPLSGAME_RESULT_OPTIONS.USER_WIN, '¡YOU WIN! :D'],
  [RSPLSGAME_RESULT_OPTIONS.COMPUTER_WIN, 'YOU LOSE :('],
]);

export const RSPLSGAME_WINS = new Map([
  [
    RSPLSGAME_VALUES.ROCK,
    [RSPLSGAME_VALUES.SCISSORS, RSPLSGAME_VALUES.LIZZARD],
  ],
  [
    RSPLSGAME_VALUES.SCISSORS,
    [RSPLSGAME_VALUES.PAPER, RSPLSGAME_VALUES.LIZZARD],
  ],
  [RSPLSGAME_VALUES.PAPER, [RSPLSGAME_VALUES.ROCK, RSPLSGAME_VALUES.SPOCK]],
  [RSPLSGAME_VALUES.LIZZARD, [RSPLSGAME_VALUES.PAPER, RSPLSGAME_VALUES.SPOCK]],
  [RSPLSGAME_VALUES.SPOCK, [RSPLSGAME_VALUES.ROCK, RSPLSGAME_VALUES.SCISSORS]],
]);
